AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("vgui/cl_health_hud.lua")
AddCSLuaFile("sh_vectors.lua")
AddCSLuaFile("sh_playermeta.lua")

include("sv_player_spawn_logic.lua")
include("shared.lua")
include("sh_vectors.lua")
include("sh_playermeta.lua")